# group_vars/all.yml

ansible_user: debian
ansible_python_interpreter: /usr/bin/python3

postgres_version: 17
db_name: mobilitydb
db_user: mobility
db_password: mobilitypass

spark_home: /opt/spark


spark_version: 4.0
scala_version: 2.13
sedona_version: 1.8.1
geotools_version: 33.1

# sedona_jar: sedona-spark-shaded-{{spark_version}}_{{scala_version}}-{{sedona_version}}.jar
# geotools_jar: geotools-wrapper-{{sedona_version}}-{{geotools_version}}.jar

# sedona_jar: sedona-spark-shaded-4.0_2.13-1.8.1.jar
# geotools_jar: geotools-wrapper-1.8.1-33.1.jar
