# inventory/hosts.yml
all:
  children:
    masters:
      hosts:
        geobenchr-sut-5:
          ansible_host: 10.122.0.7
    workers:
      hosts:
        geobenchr-sut-4:
          ansible_host: 10.122.0.107
        geobenchr-sut-3:
          ansible_host: 10.122.0.70
        geobenchr-sut-2:
          ansible_host: 10.122.0.199
        geobenchr-sut-1:
          ansible_host: 10.122.0.91