benchmark:
  sut: "MobilityDB"
  mixed: False
  nodes:
    - ""
  threads: 16
  test: False
  random_seed: 1500

queryConfigs:

  # Temporal queries
  # use
  - name: countActiveCrossingsInPeriod
    use: True
    type: temporal
    sql: >
      SELECT COUNT(*), :period_medium
      FROM crossings c
      WHERE c.traj && :period_medium;
    repetition: 10
    parameters:
      - period_medium
    
  - name: crossingsStartedAtSpecificTimeOnDay
    use: True
    type: temporal
    sql: >
      SELECT *
      FROM crossings c
      WHERE EXTRACT(HOUR FROM lower(c.traj)) = :hour AND EXTRACT(DAY FROM lower(c.traj)) = :day;
    repetition: 10
    parameters:
      - day
      - hour

  # Spatial queries
  # use
  - name: countActiveCrossingsNearIsland
    use: True
    type: spatial
    sql: >
      SELECT COUNT(*)
      FROM crossings c
      JOIN islands i
      ON ST_DWithin(c.traj, i.geom, 1000)
      WHERE i.name = :island;
    repetition: 10
    parameters:
      - island

  - name: crossingsConnectTwoGivenHarbours
    use: True
    type: spatial
    sql: >
      SELECT c.*
      FROM crossings c
      JOIN harbours h1 ON ST_DWithin(first(c.traj), h1.geom, 500)
      JOIN harbours h2 ON ST_DWithin(last(c.traj), h2.geom, 500)
      WHERE h1.name = :harbour
      AND h2.name = :harbour2;
    repetition: 10
    parameters:
      - harbour
      - harbour2

  # Spatiotemporal queries
  # use
  - name: averageDurationCrossingToGoAtHarbourInPeriod
    use: True
    type: spatiotemporal
    sql: >
      SELECT AVG(duration(c.traj)) as avg_duration
      FROM crossings c
      JOIN islands i
      ON ST_DWithin(c.traj, i.geom, 1000)
      WHERE c.traj && :period_medium
      AND i.name = :island;
    repetition: 10
    parameters:
      - island
      - period_medium

  # use
  - name: mostFrequentHarboursInPeriod
    use: True
    type: spatiotemporal
    sql: >
      SELECT h.name, COUNT(*) as crossing_count
      FROM harbours h
      JOIN crossings c
      ON ST_DWithin(last(c.traj), h.geom, 100)
      WHERE c.traj && :period_medium AND h.name = :harbour
      GROUP BY h.name
      ORDER BY crossing_count DESC;
    repetition: 10
    parameters:
      - harbour
      - period_medium