benchmark:
  sut: "MobilityDB"
  mixed: False
  nodes:
    - ""
  threads: 16
  test: False
  random_seed: 1500

queryConfigs:

  # Temporal queries
  # use
  - name: countActiveCrossingsInPeriod
    use: True
    type: temporal
    sql: >
      SELECT COUNT(*), :period_medium
      FROM crossings c
      WHERE c.traj && :period_medium;
    repetition: 10
    parameters:
      - period_medium
    
  - name: crossingsStartedAtSpecificTimeOnDay
    use: True
    type: temporal
    sql: >
      SELECT c.crossing_id
      FROM crossings c
      WHERE EXTRACT(HOUR FROM startTimestamp(c.traj)) = :hour AND DATE(startTimestamp(c.traj)) = DATE :day;
    repetition: 10
    parameters:
      - day
      - hour

  # Spatial queries
  # use
  - name: countActiveCrossingsNearIsland
    use: True
    type: spatial
    sql: > 
      SELECT COUNT(*)
      FROM crossings c
      JOIN islands i
      ON ST_DWithin(trajectory(c.traj), i.geom, 5000) 
      WHERE i.name = :island
      GROUP BY i.name;
    repetition: 10
    parameters:
      - island

  - name: crossingsConnectTwoGivenHarbours
    use: True
    type: spatial
    sql: >
      SELECT c.crossing_id
      FROM crossings c
      JOIN harbours h_start ON ST_DWithin(startValue(c.traj), h_start.geom, 1000)
      JOIN harbours h_end ON ST_DWithin(endValue(c.traj), h_end.geom, 1000)
      WHERE h_start.name = :harbour
      AND h_end.name = :port;
    repetition: 10
    parameters:
      - harbour
      - port

  # Spatiotemporal queries
  # use
  - name: averageDurationCrossingStartAtHarbourInPeriod
    use: True
    type: spatiotemporal
    sql: >
      SELECT AVG(duration(c.traj)) as avg_duration
      FROM crossings c
      JOIN harbours h
      ON ST_DWithin(startValue(c.traj), h.geom, 500)
      WHERE c.traj && :period_medium
      AND h.name = :harbour;
    repetition: 10
    parameters:
      - harbour
      - period_medium

  # use
  - name: mostFrequentHarbourInPeriod
    use: True
    type: spatiotemporal
    sql: >
      SELECT h.name, COUNT(*) as crossing_count
      FROM harbours h
      JOIN crossings c
      ON ST_DWithin(endValue(c.traj), h.geom, 500)
      WHERE c.traj && :period_medium
      GROUP BY h.name
      ORDER BY crossing_count DESC
      LIMIT 1;
    repetition: 10
    parameters:
      - period_medium